[mosip_env]
host_url='https://api-internal.dev1.mosip.net'

[mosip_websub]
hub_url='https://api-internal.dev1.mosip.net/hub/'
publish_url='https://api-internal.dev1.mosip.net/hub/'
client_secret='Test'
publisher='CREDENTIAL_SERVICE'
topic='mpartner-default-auth/CREDENTIAL_ISSUED'

[input]
file_path='/opt/taheer-mos/mosip/ida-data-seeder/auth-data-seeder/data-seeder/sample/test-import.csv'
separator='|'

# Note Providing full file path to take it to outside application.
[random_generator]
salt_max_index=1000
salt_file_store='/opt/taheer-mos/mosip/ida-data-seeder/auth-data-seeder/data-seeder/secrets-store/secret_salts.txt'
salt_bytes_size=16

zk_keys_max_index=10000
zk_keys_file_store='/opt/taheer-mos/mosip/ida-data-seeder/auth-data-seeder/data-seeder/secrets-store/zk_keys.txt'
zk_key_bytes_size=32

[key_cloak]
url='https://iam.dev1.mosip.net/auth/realms/mosip/protocol/openid-connect/token'
user_name='mosip-creser-client'
user_secret='oR3Qyr9vIfLS8dq8'

[ida]
public_key='/home/mahammedtaheer/Desktop/keys/local-ida/cred-serv.cer'
websub_secret='rIy7sOVeG34jVlO9'
cred_service_url='http://localhost:8093/idauthentication/v1/internal/callback/idchange/credential_issued/'

[datashare]
create_url='https://api-internal.dev1.mosip.net/v1/datashare/create'
policy_id='mpolicy-default-auth'
partner_id='mpartner-default-auth'
format_id='http://mosip.io/credentials/'
schema_name='MOSIPVerifiableCredential'
format_issuer='https://mosip.io/issuers/'
issuer='mpartner-default-auth'
timestamp_format='%Y-%m-%dT%H:%M:%S'
sign_p12_file='/home/mahammedtaheer/Desktop/keys/local-test-partner/partner.p12'
p12_pwd='12345'

